Repository awell-health/awell-extensions, pull requests merged in 2024-11, with the labels that each got.

#497 feat(healthie): add frozen attribute in the pushFormResponseToHealthie action
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/config/fields.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/pushFormResponseToHealthie.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/pushFormResponseToHealthie.ts
Labels: enhancement, Review effort [1-5]: 2

#498 feat(elation): add action to create a new message thread in elation
  extensions/elation/actions/__tests__/createMessageThread.ts
  extensions/elation/actions/createMessageThread.ts
  extensions/elation/actions/index.ts
  extensions/elation/client.ts
  extensions/elation/types/messageThread.ts
  extensions/elation/validation/messageThread.zod.ts
Labels: enhancement, Review effort [1-5]: 3

#499 ET-350-extend-freeze-answer-to-responses-healthie-action
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/config/fields.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.ts
Labels: Review effort [1-5]: 3

#500 the implementation is faulty and need to be reverted
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/config/fields.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/pushFormResponseToHealthie.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/pushFormResponseToHealthie.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/config/fields.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.ts
Labels: Review effort [1-5]: 2

#501 Et 350 extend freeze answer to responses healthie action
  extensions/healthie/actions/index.ts
  extensions/healthie/actions/lockFormAnswer/config/datapoints.ts
  extensions/healthie/actions/lockFormAnswer/config/fields.ts
  extensions/healthie/actions/lockFormAnswer/config/index.ts
  extensions/healthie/actions/lockFormAnswer/index.ts
  extensions/healthie/actions/lockFormAnswer/lockFormAnswerGroup.test.ts
  extensions/healthie/actions/lockFormAnswer/lockFormAnswerGroup.ts
  extensions/healthie/lib/sdk/README.md
  extensions/healthie/lib/sdk/genql/generated/schema.graphql
  extensions/healthie/lib/sdk/genql/generated/schema.ts
  extensions/healthie/lib/sdk/genql/generated/types.ts
  extensions/healthie/lib/sdk/graphql-codegen/generated/__mocks__/sdk.ts
  extensions/healthie/lib/sdk/graphql-codegen/graphql/LockFormAnswerGroup.graphql
Labels: Review effort [1-5]: 3

#502 feat(): bland.ai
  extensions/bland/CHANGELOG.md
  extensions/bland/README.md
  extensions/bland/actions/index.ts
  extensions/bland/actions/sendCall/__tests__/sendCall.test.ts
  extensions/bland/actions/sendCall/config/dataPoints.ts
  extensions/bland/actions/sendCall/config/fields.ts
  extensions/bland/actions/sendCall/config/index.ts
  extensions/bland/actions/sendCall/index.ts
  extensions/bland/actions/sendCall/sendCall.ts
  extensions/bland/actions/sendCallWithPathway/__tests__/sendCallWithPathway.test.ts
  extensions/bland/actions/sendCallWithPathway/config/dataPoints.ts
  extensions/bland/actions/sendCallWithPathway/config/fields.ts
  extensions/bland/actions/sendCallWithPathway/config/index.ts
  extensions/bland/actions/sendCallWithPathway/index.ts
  extensions/bland/actions/sendCallWithPathway/sendCallWithPathway.ts
  extensions/bland/api/client.ts
  extensions/bland/api/schema/SendCall.schema.ts
  extensions/bland/api/schema/index.ts
  extensions/bland/index.ts
  extensions/bland/lib/validatePayloadAndCreateSdk.ts
  extensions/bland/settings.ts
Labels: Review effort [1-5]: 3

#503 Add new tag attribute to elation patient
  extensions/elation/actions/createPatient.ts
  extensions/elation/actions/updatePatient.ts
  extensions/elation/types/patient.ts
Labels: Review effort [1-5]: 3

#504 Bland.ai | Support for passing data in and getting data out
  extensions/bland/README.md
  extensions/bland/actions/getCallDetails/__tests__/getCallDetails.test.ts
  extensions/bland/actions/getCallDetails/config/dataPoints.ts
  extensions/bland/actions/getCallDetails/config/fields.ts
  extensions/bland/actions/getCallDetails/config/index.ts
  extensions/bland/actions/getCallDetails/getCallDetails.ts
  extensions/bland/actions/getCallDetails/index.ts
  extensions/bland/actions/index.ts
  extensions/bland/actions/sendCall/__tests__/sendCall.test.ts
  extensions/bland/actions/sendCall/config/dataPoints.ts
  extensions/bland/actions/sendCall/config/fields.ts
  extensions/bland/actions/sendCall/sendCall.ts
  extensions/bland/actions/sendCallWithPathway/__tests__/sendCallWithPathway.test.ts
  extensions/bland/actions/sendCallWithPathway/config/dataPoints.ts
  extensions/bland/actions/sendCallWithPathway/config/fields.ts
  extensions/bland/actions/sendCallWithPathway/sendCallWithPathway.ts
  extensions/bland/api/client.ts
  extensions/bland/api/schema/GetCallDetails.schema.ts
  extensions/bland/api/schema/SendCall.schema.ts
  extensions/bland/api/schema/index.ts
Labels: Review effort [1-5]: 4

#505 ET-354-add-allergy-action-to-elation
  extensions/elation/__mocks__/client.ts
  extensions/elation/__mocks__/constants.ts
  extensions/elation/actions/addAllergy/addAllergy.test.ts
  extensions/elation/actions/addAllergy/addAllergy.ts
  extensions/elation/actions/addAllergy/config/dataPoints.ts
  extensions/elation/actions/addAllergy/config/fields.ts
  extensions/elation/actions/addAllergy/config/index.ts
  extensions/elation/actions/addAllergy/index.ts
  extensions/elation/actions/index.ts
  extensions/elation/client.ts
  extensions/elation/settings.ts
  extensions/elation/types/allergy.ts
Labels: Review effort [1-5]: 3

#508 elation resources
  extensions/elation/webhooks/appointmentCreatedOrUpdated.ts
  extensions/elation/webhooks/patientCreatedOrUpdated.ts
Labels: Review effort [1-5]: 2

#510 update action to only support one history at a time
  extensions/elation/__mocks__/constants.ts
  extensions/elation/actions/addHistories/addHistories.test.ts
  extensions/elation/actions/addHistories/addHistories.ts
  extensions/elation/actions/addHistories/config/fields.ts
  extensions/elation/actions/addHistories/index.ts
  extensions/elation/actions/addHistory/addHistory.test.ts
  extensions/elation/actions/addHistory/addHistory.ts
  extensions/elation/actions/addHistory/config/fields.ts
  extensions/elation/actions/addHistory/config/index.ts
  extensions/elation/actions/addHistory/index.ts
  extensions/elation/actions/index.ts
  extensions/elation/types/history.ts
Labels: Review effort [1-5]: 3

#511 ET-354-add-vitals
  extensions/elation/__mocks__/client.ts
  extensions/elation/__mocks__/constants.ts
  extensions/elation/actions/addVitals/addVitals.test.ts
  extensions/elation/actions/addVitals/addVitals.ts
  extensions/elation/actions/addVitals/config/dataPoints.ts
  extensions/elation/actions/addVitals/config/fields.ts
  extensions/elation/actions/addVitals/config/index.ts
  extensions/elation/actions/addVitals/index.ts
  extensions/elation/client.ts
  extensions/elation/types/vitals.ts
Labels: Review effort [1-5]: 3

#512 update index file
  extensions/elation/actions/addVitals/config/fields.ts
  extensions/elation/actions/index.ts
Labels: Review effort [1-5]: 2

#513 fix(gridspace): fix json validation and API version in 'call with grace'
  extensions/gridspace/actions/callWithGrace/callWithGrace.test.ts
  extensions/gridspace/actions/callWithGrace/config.ts
  extensions/gridspace/lib/client.ts
Labels: Review effort [1-5]: 3

#514 fix-spelling-mistake
  extensions/elation/actions/addVitals/addVitals.ts
  extensions/elation/types/vitals.ts
Labels: Review effort [1-5]: 1

#515 tidy-up-the-action
  extensions/elation/actions/addVitals/addVitals.ts
  extensions/elation/actions/addVitals/config/fields.ts
  extensions/elation/types/vitals.ts
Labels: Review effort [1-5]: 3

#516 fix parsing
  extensions/elation/__mocks__/constants.ts
  extensions/elation/actions/addVitals/addVitals.ts
Labels: Review effort [1-5]: 2

#518 add option fields to lock answer group
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/config/fields.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/pushFormResponseToHealthie.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/config/fields.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.ts
Labels: Review effort [1-5]: 3

#519 ET-377-fix-logic-for-create-patient-healthie-action
  extensions/healthie/actions/createPatient/config/fields.ts
  extensions/healthie/actions/createPatient/createPatient.test.ts
  extensions/healthie/actions/createPatient/createPatient.ts
  extensions/healthie/actions/updatePatient/config/fields.ts
  extensions/healthie/actions/updatePatient/updatePatient.test.ts
  extensions/healthie/actions/updatePatient/updatePatient.ts
Labels: Review effort [1-5]: 2

#520 fix what id we pass
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/pushFormResponseToHealthie.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.ts
Labels: Review effort [1-5]: 2

#521 make email optional in the schema
  extensions/healthie/actions/createPatient/config/fields.ts
Labels: Review effort [1-5]: 1

#522 issue-with-healthie-create-patient
  extensions/healthie/actions/createPatient/createPatient.ts
Labels: Review effort [1-5]: 2

#523 add tests
  extensions/healthie/actions/createPatient/config/fields.ts
  extensions/healthie/actions/createPatient/createPatient.test.ts
  extensions/healthie/actions/createPatient/createPatient.ts
Labels: Review effort [1-5]: 3

#524 make types more strict
  extensions/healthie/actions/createPatient/config/fields.ts
  extensions/healthie/actions/createPatient/createPatient.ts
  extensions/healthie/actions/updatePatient/config/fields.ts
  extensions/healthie/actions/updatePatient/config/index.ts
  extensions/healthie/actions/updatePatient/updatePatient.ts
Labels: Review effort [1-5]: 3

#525 Refactor update patient
  extensions/healthie/actions/createPatient/config/fields.ts
  extensions/healthie/actions/createPatient/createPatient.test.ts
  extensions/healthie/actions/createPatient/createPatient.ts
  extensions/healthie/actions/updatePatient/config/fields.ts
  extensions/healthie/actions/updatePatient/config/index.ts
  extensions/healthie/actions/updatePatient/updatePatient.test.ts
  extensions/healthie/actions/updatePatient/updatePatient.ts
Labels: Review effort [1-5]: 3

#526 feat(): get letter
  extensions/elation/__mocks__/client.ts
  extensions/elation/__mocks__/constants.ts
  extensions/elation/actions/getLetter/config/dataPoints.ts
  extensions/elation/actions/getLetter/config/fields.ts
  extensions/elation/actions/getLetter/config/index.ts
  extensions/elation/actions/getLetter/getLetter.test.ts
  extensions/elation/actions/getLetter/getLetter.ts
  extensions/elation/actions/getLetter/index.ts
  extensions/elation/actions/index.ts
  extensions/elation/client.ts
  extensions/elation/types/index.ts
  extensions/elation/types/letter.ts
Labels: Review effort [1-5]: 3

#527 ET-493-add-new-property-to-elation-user
  extensions/elation/__mocks__/constants.ts
  extensions/elation/actions/getPatient.ts
  extensions/elation/actions/getPatient/config/dataPoints.ts
  extensions/elation/actions/getPatient/config/fields.ts
  extensions/elation/actions/getPatient/config/index.ts
  extensions/elation/actions/getPatient/getPatient.test.ts
  extensions/elation/actions/getPatient/getPatient.ts
  extensions/elation/actions/getPatient/index.ts
  extensions/elation/actions/index.ts
  extensions/elation/types/patient.ts
  extensions/elation/validation/patient.zod.ts
Labels: Review effort [1-5]: 3
