Repository awell-health/awell-extensions, pull requests merged in 2024-12, with the labels that each got.

#531 feat(awell): start cf and session with one action
  extensions/awell/v1/actions/index.ts
  extensions/awell/v1/actions/startCareFlowAndSession/config/dataPoints.ts
  extensions/awell/v1/actions/startCareFlowAndSession/config/fields.ts
  extensions/awell/v1/actions/startCareFlowAndSession/config/index.ts
  extensions/awell/v1/actions/startCareFlowAndSession/index.ts
  extensions/awell/v1/actions/startCareFlowAndSession/startCareFlowAndSession.test.ts
  extensions/awell/v1/actions/startCareFlowAndSession/startCareFlowAndSession.ts
Labels: Review effort [1-5]: 3

#533 ET-577: Elation - deprecate password grant and add client credentials
  extensions/elation/actions/findAppointments.ts
  extensions/elation/actions/getPatient/getPatient.ts
  extensions/elation/client.ts
  extensions/elation/settings.ts
  extensions/elation/types/appointment.ts
  extensions/elation/validation/appointment.zod.ts
  extensions/elation/validation/settings.zod.ts
Labels: Review effort [1-5]: 3

#534 ET-602: allow multiple statuses
  extensions/awell/v1/actions/isPatientEnrolledInCareFlow/config/fields.ts
  extensions/awell/v1/actions/isPatientEnrolledInCareFlow/isPatientEnrolledInCareFlow.test.ts
Labels: Review effort [1-5]: 3

#530 Make the email validation rules more permissive
  extensions/mailchimp/settings.ts
  extensions/mailchimp/v1/actions/sendEmail/config/fields.ts
  extensions/mailchimp/v1/actions/sendEmailWithTemplate/config/fields.ts
  extensions/mailgun/settings.ts
  extensions/mailgun/v1/actions/sendEmail/config/fields.ts
  extensions/mailgun/v1/actions/sendEmailWithTemplate/config/fields.ts
  extensions/sendgrid-extension/settings.ts
  extensions/sendgrid-extension/v1/actions/addOrUpdateContact/config/fields.ts
  extensions/sendgrid-extension/v1/actions/addSuppressions/config/fields.ts
  extensions/sendgrid-extension/v1/actions/removeSuppressions/config/fields.ts
  extensions/sendgrid-extension/v1/actions/sendEmail/config/fields.ts
  extensions/sendgrid-extension/v1/actions/sendEmailWithTemplate/config/fields.ts
  src/lib/awell/getEmailValidationRegex/getEmailValidation.ts
  src/lib/awell/getEmailValidationRegex/index.ts
  src/lib/awell/index.ts
Labels: Review effort [1-5]: 3

#536 feat(elation): new action to create a care gap
  extensions/elation/actions/closeCareGap/closeCareGap.test.ts
  extensions/elation/actions/closeCareGap/closeCareGap.ts
  extensions/elation/actions/closeCareGap/config/dataPoints.ts
  extensions/elation/actions/closeCareGap/config/fields.ts
  extensions/elation/actions/closeCareGap/config/index.ts
  extensions/elation/actions/closeCareGap/index.ts
  extensions/elation/actions/createCareGap/config/dataPoints.ts
  extensions/elation/actions/createCareGap/config/fields.ts
  extensions/elation/actions/createCareGap/config/index.ts
  extensions/elation/actions/createCareGap/createCareGap.test.ts
  extensions/elation/actions/createCareGap/createCareGap.ts
  extensions/elation/actions/createCareGap/index.ts
  extensions/elation/actions/createReferralOrder/createReferralOrder.test.ts
  extensions/elation/client.ts
  extensions/elation/types/careGap.ts
  extensions/elation/types/index.ts
  extensions/elation/validation/careGap.zod.ts
Labels: Review effort [1-5]: 4

#537 ET-614: additional logging for SFDC
  extensions/sfdc/actions/createLead/createLead.ts
  extensions/sfdc/actions/updateLead/updateLead.ts
Labels: Review effort [1-5]: 2

#538 ET-599: remote single select - store full json option
  extensions/collectData/v1/actions/remoteSingleSelect/config/dataPoint.ts
  extensions/collectData/v1/actions/remoteSingleSelect/config/fields.ts
  extensions/collectData/v1/actions/remoteSingleSelect/remoteSingleSelect.ts
Labels: Review effort [1-5]: 2

#542 Move Healthie SDK out of the repo
  .pnp.cjs
  .yarn/cache/@awell-health-healthie-sdk-npm-0.1.1-07daa17318-31ac37a940.zip
  extensions/healthie/actions/createAppointment/createAppointment.test.ts
  extensions/healthie/actions/createGoal/createGoal.test.ts
  extensions/healthie/actions/createPatient/createPatient.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/pushFormResponseToHealthie.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.test.ts
  extensions/healthie/actions/deleteGoal/deleteGoal.test.ts
  extensions/healthie/actions/getSetPasswordLink/getSetPasswordLink.test.ts
  extensions/healthie/actions/lockFormAnswer/lockFormAnswerGroup.test.ts
  extensions/healthie/actions/updatePatient/updatePatient.test.ts
  extensions/healthie/lib/sdk/README.md
  extensions/healthie/lib/sdk/genql/HealthieSdk.ts
  extensions/healthie/lib/sdk/genql/generateSdk.ts
  extensions/healthie/lib/sdk/genql/generated/index.ts
  extensions/healthie/lib/sdk/genql/generated/runtime/batcher.ts
  extensions/healthie/lib/sdk/genql/generated/runtime/createClient.ts
  extensions/healthie/lib/sdk/genql/generated/runtime/error.ts
  extensions/healthie/lib/sdk/genql/generated/runtime/fetcher.ts
  extensions/healthie/lib/sdk/genql/generated/runtime/generateGraphqlOperation.ts
  extensions/healthie/lib/sdk/genql/generated/runtime/index.ts
  extensions/healthie/lib/sdk/genql/generated/runtime/linkTypeMap.ts
  extensions/healthie/lib/sdk/genql/generated/runtime/typeSelection.ts
  extensions/healthie/lib/sdk/genql/generated/runtime/types.ts
  extensions/healthie/lib/sdk/genql/generated/schema.graphql
  extensions/healthie/lib/sdk/genql/generated/schema.ts
  extensions/healthie/lib/sdk/genql/generated/types.ts
  extensions/healthie/lib/sdk/genql/index.ts
  extensions/healthie/lib/sdk/validatePayloadAndCreateSdk.ts
  package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#543 ET-712 | fix(mailgun): support multiple email addresses
  extensions/mailgun/v1/actions/sendEmail/config/fields.ts
  extensions/mailgun/v1/actions/sendEmail/sendEmail.ts
  extensions/mailgun/v1/actions/sendEmailWithTemplate/config/fields.ts
  extensions/mailgun/v1/actions/sendEmailWithTemplate/sendEmailWithTemplate.ts
  src/lib/awell/getEmailValidationRegex/getEmailValidation.test.ts
  src/lib/awell/getEmailValidationRegex/getEmailValidation.ts
Labels: Review effort [1-5]: 3
