Repository awell-health/awell-extensions, pull requests merged in 2024-09, with the labels that each got.

#462 Add Cdium PR agent workflow
  .github/workflows/pr_agent.yml
Labels: enhancement, configuration changes, Review effort [1-5]: 2

#465 fix(shelly): formatting - return HTML
  .pnp.cjs
  .yarn/cache/@types-sanitize-html-npm-2.13.0-75e761ecaa-a32c67bdf8.zip
  .yarn/cache/htmlparser2-npm-8.0.2-5d9f901bb6-29167a0f92.zip
  .yarn/cache/is-plain-object-npm-5.0.0-285b70faa3-e32d27061e.zip
  .yarn/cache/marked-npm-14.1.2-9af20f3731-47636a6c4e.zip
  .yarn/cache/nanoid-npm-3.3.7-98824ba130-d36c427e53.zip
  .yarn/cache/parse-srcset-npm-1.0.2-8acc142245-3a0380380c.zip
  .yarn/cache/postcss-npm-8.4.47-2f4d4be1fa-f78440a9d8.zip
  .yarn/cache/sanitize-html-npm-2.13.0-32b89ad1cd-d886023283.zip
  .yarn/cache/source-map-js-npm-1.2.1-b9a47d7e1a-4eb0cd997c.zip
  extensions/shelly/actions/categorizeMessage/categorizeMessage.test.ts
  extensions/shelly/actions/categorizeMessage/categorizeMessage.ts
  extensions/shelly/actions/summarizeCareFlow/summarizeCareFlow.test.ts
  extensions/shelly/actions/summarizeCareFlow/summarizeCareFlow.ts
  extensions/shelly/actions/summarizeForm/summarizeForm.test.ts
  extensions/shelly/actions/summarizeForm/summarizeForm.ts
  package.json
  src/utils/index.ts
  src/utils/markdownToHtml/index.ts
  src/utils/markdownToHtml/markdownToHtml.test.ts
  src/utils/markdownToHtml/markdownToHtml.ts
  yarn.lock
Labels: enhancement, dependencies, tests, Review effort [1-5]: 3

#464 Hackathon Shelly Extension: final improvements
  extensions/shelly/actions/summarizeCareFlow/config/fields.ts
  extensions/shelly/actions/summarizeCareFlow/lib/summarizeCareFlowWithLLM/constants.ts
  extensions/shelly/actions/summarizeCareFlow/summarizeCareFlowRealOpenAI.test.ts
  extensions/shelly/actions/summarizeForm/__mocks__/formDefinitionResponse.ts
  extensions/shelly/actions/summarizeForm/config/fields.ts
  extensions/shelly/actions/summarizeForm/lib/getResponseText/getResponseText.ts
  extensions/shelly/actions/summarizeForm/lib/summarizeFormWithLLM/constants.ts
  extensions/shelly/actions/summarizeForm/summarizeFormRealOpenAI.test.ts
Labels: enhancement, tests, Review effort [1-5]: 3
