Repository awell-health/awell-extensions, pull requests merged in 2024-10, with the labels that each got.

#471 feat(): data exchange for multiple forms
  extensions/healthie/actions/dataExchange/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/__mocks__/formDefinitionResponse.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/__mocks__/formResponseResponse.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/__mocks__/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/__mocks__/pathwayActivitiesResponse.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/config/datapoints.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/config/fields.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/config/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/logs/getSubActivityLogs/getSubActivityLogs.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/logs/getSubActivityLogs/getSubActivityLogs.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/logs/getSubActivityLogs/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/logs/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/pushFormResponseToHealthie.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponseToHealthie/pushFormResponseToHealthie.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/__mocks__/formDefinitionResponse.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/__mocks__/formResponseResponse.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/__mocks__/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/__mocks__/pathwayActivitiesResponse.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/config/datapoints.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/config/fields.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/config/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/logs/getSubActivityLogs/getSubActivityLogs.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/logs/getSubActivityLogs/getSubActivityLogs.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/logs/getSubActivityLogs/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/logs/index.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.test.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.ts
  extensions/healthie/actions/dataExchange/shared/errors.ts
  extensions/healthie/actions/dataExchange/shared/index.ts
  extensions/healthie/actions/index.ts
  extensions/healthie/lib/sdk/genql/generated/schema.graphql
  extensions/healthie/lib/sdk/genql/generated/schema.ts
  extensions/healthie/lib/sdk/genql/generated/types.ts
  extensions/twilio/v2/actions/sendSmsDuringBusinessHours/sendSmsDuringBusinessHours.test.ts
  src/lib/awell/getAllFormsInCurrentStep/__testdata__/formDefinitionResponse.ts
  src/lib/awell/getAllFormsInCurrentStep/__testdata__/formResponseResponse.ts
  src/lib/awell/getAllFormsInCurrentStep/__testdata__/index.ts
  src/lib/awell/getAllFormsInCurrentStep/__testdata__/pathwayActivitiesResponse.ts
  src/lib/awell/getAllFormsInCurrentStep/getAllFormsInCurrentStep.test.ts
  src/lib/awell/getAllFormsInCurrentStep/getAllFormsInCurrentStep.ts
  src/lib/awell/getAllFormsInCurrentStep/index.ts
  src/lib/awell/index.ts
Labels: enhancement, tests, Review effort [1-5]: 4

#472 awell pathway id into salesforce
  extensions/sfdc/actions/createLead/config/fields.ts
  extensions/sfdc/actions/createLead/createLead.test.ts
  extensions/sfdc/actions/createLead/createLead.ts
Labels: enhancement, Review effort [1-5]: 2

#473 Minor Message Categorization Prompt Update
  extensions/shelly/actions/categorizeMessage/lib/categorizeMessageWithLLM/constants.ts
Labels: enhancement, Review effort [1-5]: 2

#474 AI Action: Generate personalized messages
  extensions/shelly/actions/generateMessage/config/datapoints.ts
  extensions/shelly/actions/generateMessage/config/fields.ts
  extensions/shelly/actions/generateMessage/config/index.ts
  extensions/shelly/actions/generateMessage/generateMessage.test.ts
  extensions/shelly/actions/generateMessage/generateMessage.ts
  extensions/shelly/actions/generateMessage/generateMessageRealOpenAI.test.ts
  extensions/shelly/actions/generateMessage/index.ts
  extensions/shelly/actions/generateMessage/lib/generateMessageWithLLM/constants.ts
  extensions/shelly/actions/generateMessage/lib/generateMessageWithLLM/generateMessageWithLLM.test.ts
  extensions/shelly/actions/generateMessage/lib/generateMessageWithLLM/generateMessageWithLLM.ts
  extensions/shelly/actions/generateMessage/lib/generateMessageWithLLM/generateMessageWithLLMRealOpenAI.test.ts
  extensions/shelly/actions/generateMessage/lib/generateMessageWithLLM/index.ts
Labels: enhancement, tests, Review effort [1-5]: 3

#475 Enable generate message action
  extensions/shelly/actions/index.ts
Labels: enhancement, Review effort [1-5]: 1

#477 feat(gridspace): initial gridspace extension
  extensions/gridspace/CHANGELOG.md
  extensions/gridspace/README.md
  extensions/gridspace/actions/callWithGrace/callWithGrace.test.ts
  extensions/gridspace/actions/callWithGrace/callWithGrace.ts
  extensions/gridspace/actions/callWithGrace/config.ts
  extensions/gridspace/actions/callWithGrace/index.ts
  extensions/gridspace/actions/index.ts
  extensions/gridspace/index.ts
  extensions/gridspace/lib/client.ts
  extensions/gridspace/lib/index.ts
  extensions/gridspace/settings.ts
  extensions/index.ts
Labels: enhancement, Review effort [1-5]: 3

#478 AI Actions improvements
  extensions/shelly/actions/categorizeMessage/categorizeMessage.ts
  extensions/shelly/actions/categorizeMessage/lib/categorizeMessageWithLLM/categorizeMessageWithLLM.ts
  extensions/shelly/actions/generateMessage/config/fields.ts
  extensions/shelly/actions/generateMessage/generateMessage.test.ts
  extensions/shelly/actions/generateMessage/generateMessage.ts
  extensions/shelly/actions/generateMessage/generateMessageRealOpenAI.test.ts
  extensions/shelly/actions/generateMessage/lib/generateMessageWithLLM/constants.ts
  extensions/shelly/actions/generateMessage/lib/generateMessageWithLLM/generateMessageWithLLM.test.ts
  extensions/shelly/actions/generateMessage/lib/generateMessageWithLLM/generateMessageWithLLM.ts
  extensions/shelly/actions/generateMessage/lib/generateMessageWithLLM/generateMessageWithLLMRealOpenAI.test.ts
  extensions/shelly/actions/summarizeCareFlow/lib/summarizeCareFlowWithLLM/summarizeCareFlowWithLLM.test.ts
  extensions/shelly/actions/summarizeCareFlow/lib/summarizeCareFlowWithLLM/summarizeCareFlowWithLLM.ts
  extensions/shelly/actions/summarizeCareFlow/summarizeCareFlow.ts
  extensions/shelly/actions/summarizeForm/config/fields.ts
  extensions/shelly/actions/summarizeForm/summarizeForm.test.ts
  extensions/shelly/actions/summarizeForm/summarizeForm.ts
  extensions/shelly/actions/summarizeForm/summarizeFormRealOpenAI.test.ts
  extensions/shelly/actions/summarizeFormsInStep/summarizeFormsInStep.test.ts
  extensions/shelly/actions/summarizeFormsInStep/summarizeFormsInStep.ts
  extensions/shelly/actions/summarizeFormsInStep/summarizeFormsInStepRealOpenAI.test.ts
  extensions/shelly/lib/getFormResponseText/getFormResponseText.ts
  extensions/shelly/lib/summarizeFormWithLLM/constants.ts
  extensions/shelly/lib/summarizeFormWithLLM/summarizeFormWithLLM.test.ts
  extensions/shelly/lib/summarizeFormWithLLM/summarizeFormWithLLM.ts
Labels: enhancement, tests, Review effort [1-5]: 3

#481 feat(gridspace): implement uploadContactToCampaign action in gridspace extension
  extensions/gridspace/actions/callWithGrace/callWithGrace.test.ts
  extensions/gridspace/actions/callWithGrace/callWithGrace.ts
  extensions/gridspace/actions/index.ts
  extensions/gridspace/actions/uploadContactToCampaign/config.ts
  extensions/gridspace/actions/uploadContactToCampaign/index.ts
  extensions/gridspace/actions/uploadContactToCampaign/uploadContactToCampaign.test.ts
  extensions/gridspace/actions/uploadContactToCampaign/uploadContactToCampaign.ts
  extensions/gridspace/lib/client.ts
  extensions/gridspace/settings.ts
Labels: enhancement, tests, Review effort [1-5]: 3

#485 fix(healthie): retry getSetPasswordLink using exponential backoff
  extensions/healthie/actions/getSetPasswordLink/getSetPasswordLink.test.ts
  extensions/healthie/actions/getSetPasswordLink/getSetPasswordLink.ts
Labels: High priority, tests, Review effort [1-5]: 3, Bug fix

#488 TP-2574: add location as a new data point in "get booking" action in cal.com
  extensions/calDotCom/actions/getBooking/config/dataPoints.ts
  extensions/calDotCom/actions/getBooking/getBooking.test.ts
  extensions/calDotCom/actions/getBooking/getBooking.ts
  extensions/calDotCom/schema.ts
Labels: enhancement, tests, Review effort [1-5]: 2

#489 feat(gridspace): complete uploadContactToCampaign activity after api call
  extensions/gridspace/actions/uploadContactToCampaign/uploadContactToCampaign.test.ts
  extensions/gridspace/actions/uploadContactToCampaign/uploadContactToCampaign.ts
Labels: enhancement, tests, Review effort [1-5]: 2

#492 TP-2606: update gridspace uploadContactTocampaign action to return data poitn
  extensions/gridspace/actions/uploadContactToCampaign/config.ts
  extensions/gridspace/actions/uploadContactToCampaign/uploadContactToCampaign.test.ts
  extensions/gridspace/actions/uploadContactToCampaign/uploadContactToCampaign.ts
  extensions/gridspace/lib/client.ts
Labels: extension

#493 ET-325: allow updating identifier
  extensions/awell/README.md
  extensions/awell/v1/actions/addIdentifierToPatient/addIdentifierToPatient.test.ts
  extensions/awell/v1/actions/addIdentifierToPatient/addIdentifierToPatient.ts
  src/utils/getNextDateWithinBusinessHours/getNextDateWithinBusinessHours.test.ts
Labels: Review effort [1-5]: 3

#495 TP-2617: extend create appointment action
  extensions/healthie/actions/createAppointment/config/fields.ts
  extensions/healthie/actions/createAppointment/createAppointment.test.ts
  extensions/healthie/actions/createAppointment/createAppointment.ts
  extensions/healthie/actions/createAppointment/lib/errors.ts
Labels: Review effort [1-5]: 3
