Repository awell-health/awell-extensions, pull requests merged in 2025-03, with the labels that each got.

#591 Et 886 add text em all extension
  .pnp.cjs
  .yarn/cache/@types-crypto-js-npm-4.2.2-21357d525e-a40fc5a921.zip
  .yarn/cache/crypto-js-npm-4.2.0-d6f7744e63-c7bcc56a6e.zip
  .yarn/cache/oauth-1.0a-npm-2.2.6-bcd1a18561-5807a52077.zip
  extensions/index.ts
  extensions/text-em-all/CHANGELOG.md
  extensions/text-em-all/README.md
  extensions/text-em-all/actions/createCallBroadcast/__testdata__/CreateCallBroadcast.mock.ts
  extensions/text-em-all/actions/createCallBroadcast/config.ts
  extensions/text-em-all/actions/createCallBroadcast/createCallBroadcast.test.ts
  extensions/text-em-all/actions/createCallBroadcast/createCallBroadcast.ts
  extensions/text-em-all/actions/createCallBroadcast/index.ts
  extensions/text-em-all/actions/createCallBroadcast/types.ts
  extensions/text-em-all/actions/createSMSBroadcast/__testdata__/CreateSMSBroadcast.mock.ts
  extensions/text-em-all/actions/createSMSBroadcast/config.ts
  extensions/text-em-all/actions/createSMSBroadcast/createSMSBroadcast.test.ts
  extensions/text-em-all/actions/createSMSBroadcast/createSMSBroadcast.ts
  extensions/text-em-all/actions/createSMSBroadcast/index.ts
  extensions/text-em-all/actions/createSMSBroadcast/types.ts
  extensions/text-em-all/actions/index.ts
  extensions/text-em-all/actions/types.ts
  extensions/text-em-all/actions/utils/validateJsonField.ts
  extensions/text-em-all/index.ts
  extensions/text-em-all/lib/client.ts
  extensions/text-em-all/lib/index.ts
  extensions/text-em-all/settings.ts
  extensions/text-em-all/webhooks/broadcastStatusChange.ts
  extensions/text-em-all/webhooks/index.ts
  extensions/text-em-all/webhooks/types.ts
  package.json
  yarn.lock
Labels: Review effort 4/5

#594 TP-2947: Add new elation action to check patient tags
  extensions/elation/README.md
  extensions/elation/actions/checkPatientTags/checkPatientTags.test.ts
  extensions/elation/actions/checkPatientTags/checkPatientTags.ts
  extensions/elation/actions/checkPatientTags/checkPatientTagsRealOpenAI.test.ts
  extensions/elation/actions/checkPatientTags/config/dataPoints.ts
  extensions/elation/actions/checkPatientTags/config/fields.ts
  extensions/elation/actions/checkPatientTags/config/index.ts
  extensions/elation/actions/checkPatientTags/index.ts
  extensions/elation/actions/checkPatientTags/lib/checkTagsWithLLM/checkTagsWithLLM.ts
  extensions/elation/actions/checkPatientTags/lib/checkTagsWithLLM/parser.ts
  extensions/elation/actions/checkPatientTags/lib/checkTagsWithLLM/prompt.ts
  extensions/elation/actions/checkPatientTags/lib/evaluateCheckTags.ts
  extensions/elation/actions/index.ts
Labels: ai-action, Review effort 4/5

#596 add more logs
  extensions/text-em-all/lib/client.ts
Labels: Review effort 2/5

#597 add better error handling
  extensions/text-em-all/actions/createCallBroadcast/createCallBroadcast.ts
  extensions/text-em-all/actions/createSMSBroadcast/createSMSBroadcast.ts
  extensions/text-em-all/actions/types.ts
  extensions/text-em-all/lib/client.ts
Labels: Review effort 2/5

#598 feat(hello-world): tweak log action to support regression tests
  extensions/hello-world/actions/__tests__/log.ts
  extensions/hello-world/actions/log.ts
  extensions/hello-world/settings.ts
Labels: Review effort 2/5

#600 feat(awell-tasks): add event when last task has no performer
  extensions/awellTasks/actions/getLastTaskPerformer/getLastTaskPerformer.test.ts
  extensions/awellTasks/actions/getLastTaskPerformer/getLastTaskPerformer.ts
Labels: Review effort 3/5

#602 fix key of the field
  extensions/braze/settings.ts
Labels: Review effort 1/5

#604 REV-24 | feat(medplum): get service request
  extensions/medplum/actions/getAppointment/getAppointment.ts
  extensions/medplum/actions/getServiceRequest/__testdata__/ServiceRequest.mock.ts
  extensions/medplum/actions/getServiceRequest/config/dataPoints.ts
  extensions/medplum/actions/getServiceRequest/config/fields.ts
  extensions/medplum/actions/getServiceRequest/config/index.ts
  extensions/medplum/actions/getServiceRequest/getServiceRequest.test.ts
  extensions/medplum/actions/getServiceRequest/getServiceRequest.ts
  extensions/medplum/actions/getServiceRequest/index.ts
  extensions/medplum/actions/index.ts
  extensions/medplum/utils/extractResourceId/extractResourceId.test.ts
Labels: Review effort 3/5

#606 Rev-54: Improve Summarize Form AI Action to Maintain Question Order
  extensions/shelly/README.md
  extensions/shelly/actions/summarizeForm/config/fields.ts
  extensions/shelly/actions/summarizeForm/summarizeForm.test.ts
  extensions/shelly/actions/summarizeForm/summarizeForm.ts
  extensions/shelly/actions/summarizeForm/summarizeFormRealOpenAI.test.ts
  extensions/shelly/lib/getFormResponseText/getFormResponseText.ts
  extensions/shelly/lib/summarizeFormWithLLM/prompt.ts
  extensions/shelly/lib/summarizeFormWithLLM/summarizeFormWithLLM.ts
Labels: ai-action, Review effort 3/5

#599 add patient timezone as an optional field when updating the patient
  extensions/awell/v1/actions/updatePatient/config/fields.ts
  extensions/awell/v1/actions/updatePatient/config/getTimezones.ts
  extensions/awell/v1/actions/updatePatient/updatePatient.ts
  extensions/awell/v1/gql/graphql.ts
Labels: Review effort 3/5

#609 REV-47 | fix(timezones): use package instead of relying on node
  .pnp.cjs
  .yarn/cache/tzdata-npm-1.0.43-a69ae0d968-5b6bd03588.zip
  extensions/awell/v1/actions/updatePatient/config/getTimezones.ts
  extensions/awell/v1/actions/updatePatient/updatePatient.test.ts
  package.json
  yarn.lock
Labels: Review effort 3/5

#610 ET-1058: Make Summarize Track Outcome AI Action production ready
  extensions/shelly/actions/summarizeForm/summarizeForm.test.ts
  extensions/shelly/actions/summarizeForm/summarizeForm.ts
  extensions/shelly/actions/summarizeForm/summarizeFormRealOpenAI.test.ts
  extensions/shelly/actions/summarizeTrackOutcome/__mocks__/mockTrackData.ts
  extensions/shelly/actions/summarizeTrackOutcome/lib/summarizeTrackOutcomeWithLLM/prompt.ts
  extensions/shelly/actions/summarizeTrackOutcome/lib/summarizeTrackOutcomeWithLLM/summarizeTrackOutcomeWithLLM.evaluate.ts
  extensions/shelly/actions/summarizeTrackOutcome/summarizeTrackOutcome.test.ts
  extensions/shelly/actions/summarizeTrackOutcome/summarizeTrackOutcome.ts
  extensions/shelly/actions/summarizeTrackOutcome/summarizeTrackOutcomeRealOpenAI.test.ts
  extensions/shelly/lib/getCareFlowDetails/__mocks__/index.ts
  extensions/shelly/lib/getCareFlowDetails/__mocks__/pathwayDetailsResponse.ts
  extensions/shelly/lib/getCareFlowDetails/__mocks__/publishedDefinitionsResponse.ts
  extensions/shelly/lib/getCareFlowDetails/getCareFlowDetails.test.ts
  extensions/shelly/lib/getCareFlowDetails/getCareFlowDetails.ts
  extensions/shelly/lib/getCareFlowDetails/index.ts
  extensions/shelly/lib/getTrackData/__mocks__/formDefinitionResponse.ts
  extensions/shelly/lib/getTrackData/__mocks__/formResponseResponse.ts
  extensions/shelly/lib/getTrackData/__mocks__/index.ts
  extensions/shelly/lib/getTrackData/__mocks__/messageResponse.ts
  extensions/shelly/lib/getTrackData/__mocks__/pathwayActivitiesResponse.ts
  extensions/shelly/lib/getTrackData/__mocks__/pathwayDataPointsResponse.ts
  extensions/shelly/lib/getTrackData/__mocks__/pathwayElementsResponse.ts
  extensions/shelly/lib/getTrackData/__mocks__/pathwayResponse.ts
  extensions/shelly/lib/getTrackData/getTrackData.test.ts
  extensions/shelly/lib/getTrackData/getTrackData.ts
  extensions/shelly/lib/getTrackData/index.ts
  extensions/shelly/lib/getTrackData/types.ts
Labels: ai-action, Review effort 4/5

#611 fix(elation): remove webhook logs not parsed appropriately by GCP
  extensions/elation/webhooks/appointmentCreatedOrUpdated.ts
  extensions/elation/webhooks/patientCreatedOrUpdated.ts
Labels: Review effort 2/5

#614 REV-96 | feat(hubspot): create or update contact
  extensions/hubspot/README.md
  extensions/hubspot/actions/createOrUpdateContact/config/datapoints.ts
  extensions/hubspot/actions/createOrUpdateContact/config/fields.ts
  extensions/hubspot/actions/createOrUpdateContact/config/index.ts
  extensions/hubspot/actions/createOrUpdateContact/createOrUpdateContact.test.ts
  extensions/hubspot/actions/createOrUpdateContact/createOrUpdateContact.ts
  extensions/hubspot/actions/createOrUpdateContact/helpers.ts
  extensions/hubspot/actions/createOrUpdateContact/index.ts
  extensions/hubspot/actions/index.ts
Labels: Review effort 4/5

#615 Rev-109: Elation find appointments with AI - improvements
  extensions/elation/README.md
  extensions/elation/actions/cancelAppointments/cancelAppointments.test.ts
  extensions/elation/actions/cancelAppointments/cancelAppointments.ts
  extensions/elation/actions/cancelAppointments/cancelAppointmentsWithAIRealOpenAI.test.ts
  extensions/elation/actions/findAppointmentsWithAI/findAppointmentsWithAI.ts
  extensions/elation/actions/findFutureAppointment/findFutureAppointment.test.ts
  extensions/elation/actions/findFutureAppointment/findFutureAppointment.ts
  extensions/elation/actions/findFutureAppointment/findFutureAppointmentRealOpenAI.test.ts
Labels: Review effort 4/5

#616 fix(elation): include service_location when canceling an appointment
  extensions/elation/actions/cancelAppointments/cancelAppointments.ts
Labels: Review effort 2/5

#617 Rev-110: Adjust formatting in AI generated track outcome sumary
  extensions/shelly/actions/summarizeForm/summarizeForm.test.ts
  extensions/shelly/actions/summarizeForm/summarizeForm.ts
  extensions/shelly/actions/summarizeForm/summarizeFormRealOpenAI.test.ts
  extensions/shelly/actions/summarizeTrackOutcome/lib/summarizeTrackOutcomeWithLLM/prompt.ts
  extensions/shelly/actions/summarizeTrackOutcome/summarizeTrackOutcome.test.ts
  extensions/shelly/actions/summarizeTrackOutcome/summarizeTrackOutcome.ts
  extensions/shelly/actions/summarizeTrackOutcome/summarizeTrackOutcomeRealOpenAI.test.ts
Labels: Review effort 2/5

#618 fix(elation): cancel an appointment via api
  extensions/elation/actions/cancelAppointments/cancelAppointments.ts
Labels: Review effort 2/5

#620 Vis 109 update to use v2flows instead of deprecated flows
  extensions/twilio/common/createSdkClient.ts
  extensions/twilio/settings.ts
  extensions/twilio/v1/actions/__tests__/smsNotification.ts
  extensions/twilio/v2/actions/createFlowExecution/createFlowExecution.ts
  extensions/twilio/v2/actions/getMessages/getMessages.test.ts
  extensions/twilio/v2/actions/sendSms/sendSms.test.ts
  extensions/twilio/v2/actions/sendSmsDuringBusinessHours/sendSmsDuringBusinessHours.test.ts
  extensions/twilio/v2/actions/sendSmsWithMessagingSid/sendSmsWithMessagingService.test.ts
Labels: Review effort 3/5

#622 add-new-region-to-twilio
  extensions/twilio/common/createSdkClient.ts
Labels: Review effort 2/5
