Repository awell-health/awell-extensions, pull requests merged in 2025-01, with the labels that each got.

#544 feat(ehrs): Epic & Cerner
  extensions/cerner/CHANGELOG.md
  extensions/cerner/README.md
  extensions/cerner/actions/createClinicalNote/config/datapoints.ts
  extensions/cerner/actions/createClinicalNote/config/fields.ts
  extensions/cerner/actions/createClinicalNote/config/index.ts
  extensions/cerner/actions/createClinicalNote/createClinicalNote.test.ts
  extensions/cerner/actions/createClinicalNote/createClinicalNote.ts
  extensions/cerner/actions/createClinicalNote/index.ts
  extensions/cerner/actions/createPatient/config/datapoints.ts
  extensions/cerner/actions/createPatient/config/fields.ts
  extensions/cerner/actions/createPatient/config/index.ts
  extensions/cerner/actions/createPatient/createPatient.test.ts
  extensions/cerner/actions/createPatient/createPatient.ts
  extensions/cerner/actions/createPatient/index.ts
  extensions/cerner/actions/getAppointment/config/datapoints.ts
  extensions/cerner/actions/getAppointment/config/fields.ts
  extensions/cerner/actions/getAppointment/config/index.ts
  extensions/cerner/actions/getAppointment/getAppointment.test.ts
  extensions/cerner/actions/getAppointment/getAppointment.ts
  extensions/cerner/actions/getAppointment/index.ts
  extensions/cerner/actions/getPatient/config/datapoints.ts
  extensions/cerner/actions/getPatient/config/fields.ts
  extensions/cerner/actions/getPatient/config/index.ts
  extensions/cerner/actions/getPatient/getPatient.test.ts
  extensions/cerner/actions/getPatient/getPatient.ts
  extensions/cerner/actions/getPatient/index.ts
  extensions/cerner/actions/index.ts
  extensions/cerner/index.ts
  extensions/cerner/settings.ts
  extensions/epic/CHANGELOG.md
  extensions/epic/README.md
  extensions/epic/actions/createClinicalNote/config/datapoints.ts
  extensions/epic/actions/createClinicalNote/config/fields.ts
  extensions/epic/actions/createClinicalNote/config/index.ts
  extensions/epic/actions/createClinicalNote/createClinicalNote.test.ts
  extensions/epic/actions/createClinicalNote/createClinicalNote.ts
  extensions/epic/actions/createClinicalNote/index.ts
  extensions/epic/actions/createPatient/config/datapoints.ts
  extensions/epic/actions/createPatient/config/fields.ts
  extensions/epic/actions/createPatient/config/index.ts
  extensions/epic/actions/createPatient/createPatient.test.ts
  extensions/epic/actions/createPatient/createPatient.ts
  extensions/epic/actions/createPatient/index.ts
  extensions/epic/actions/getAppointment/config/datapoints.ts
  extensions/epic/actions/getAppointment/config/fields.ts
  extensions/epic/actions/getAppointment/config/index.ts
  extensions/epic/actions/getAppointment/getAppointment.test.ts
  extensions/epic/actions/getAppointment/getAppointment.ts
  extensions/epic/actions/getAppointment/index.ts
  extensions/epic/actions/getPatient/config/datapoints.ts
  extensions/epic/actions/getPatient/config/fields.ts
  extensions/epic/actions/getPatient/config/index.ts
  extensions/epic/actions/getPatient/getPatient.test.ts
  extensions/epic/actions/getPatient/getPatient.ts
  extensions/epic/actions/getPatient/index.ts
  extensions/epic/actions/index.ts
  extensions/epic/index.ts
  extensions/epic/settings.ts
  extensions/index.ts
Labels: Review effort [1-5]: 4

#545 ET-764: store `signed_by` from Elation letter
  extensions/elation/actions/getLetter/config/dataPoints.ts
  extensions/elation/actions/getLetter/getLetter.test.ts
  extensions/elation/actions/getLetter/getLetter.ts
  extensions/elation/types/letter.ts
Labels: Review effort [1-5]: 2

#547 chore(review): update patient tags
  extensions/elation/actions/updatePatientTags/updatePatientTags.ts
Labels: Review effort [1-5]: 4

#548 ET-781: retrieve all comments from Task Service
  .pnp.cjs
  .yarn/cache/@asamuzakjp-css-color-npm-2.8.2-9a49769c6e-998885b5de.zip
  .yarn/cache/@csstools-color-helpers-npm-5.0.1-746052a15b-4cb25b3499.zip
  .yarn/cache/@csstools-css-calc-npm-2.1.1-e5c57a9daf-60e8808c26.zip
  .yarn/cache/@csstools-css-color-parser-npm-3.0.7-3545815777-efceb60608.zip
  .yarn/cache/@csstools-css-parser-algorithms-npm-3.0.4-ace8f522a1-dfb6926218.zip
  .yarn/cache/@csstools-css-tokenizer-npm-3.0.3-c884a41159-6baa3160e4.zip
  .yarn/cache/@parcel-watcher-darwin-arm64-npm-2.4.1-7294eb72cd-10.zip
  .yarn/cache/@parcel-watcher-darwin-x64-npm-2.4.1-e905ba5776-10.zip
  .yarn/cache/@types-jsdom-npm-21.1.7-b9d35cbe67-a5ee54aec8.zip
  .yarn/cache/@types-tough-cookie-npm-4.0.5-8c5e2162e1-01fd82efc8.zip
  .yarn/cache/agent-base-npm-7.1.3-b2c16e72fb-3db6d8d465.zip
  .yarn/cache/cssstyle-npm-4.2.1-744e7b204d-e287234f2f.zip
  .yarn/cache/data-urls-npm-5.0.0-4b58b89bfe-5c40568c31.zip
  .yarn/cache/decimal.js-npm-10.4.3-e7d483387c-de663a7bc4.zip
  .yarn/cache/form-data-npm-4.0.1-f1a27a1c2e-6adb1cff55.zip
  .yarn/cache/html-encoding-sniffer-npm-4.0.0-5f6627070d-e86efd4932.zip
  .yarn/cache/https-proxy-agent-npm-7.0.6-27a95c2690-784b628cbd.zip
  .yarn/cache/is-potential-custom-element-name-npm-1.0.1-f352f606f8-ced7bbbb64.zip
  .yarn/cache/jsdom-npm-26.0.0-01acafd498-8c230ee465.zip
  .yarn/cache/lru-cache-npm-11.0.2-72e1eedbe6-25fcb66e9d.zip
  .yarn/cache/nwsapi-npm-2.2.16-9ae9928240-1e5e086cdd.zip
  .yarn/cache/parse5-npm-7.2.1-c48f333f28-fd1a8ad154.zip
  .yarn/cache/rrweb-cssom-npm-0.8.0-0c92f2366d-07521ee36f.zip
  .yarn/cache/saxes-npm-6.0.0-31558949f5-97b50daf6c.zip
  .yarn/cache/symbol-tree-npm-3.2.4-fe70cdb75b-c09a00aadf.zip
  .yarn/cache/tldts-core-npm-6.1.71-cc68dd578b-9bed9e0679.zip
  .yarn/cache/tldts-npm-6.1.71-74ea01b8d1-6a3e9ebf14.zip
  .yarn/cache/tough-cookie-npm-5.1.0-a5655b81b0-01908de89d.zip
  .yarn/cache/tr46-npm-5.0.0-d15754040d-29155adb16.zip
  .yarn/cache/w3c-xmlserializer-npm-5.0.0-589edd7bff-d78f59e6b4.zip
  .yarn/cache/webidl-conversions-npm-7.0.0-e8c8e30c68-4c4f65472c.zip
  .yarn/cache/whatwg-url-npm-14.1.0-ed62f15e7a-3afd325de6.zip
  .yarn/cache/xml-name-validator-npm-5.0.0-0e0ec66944-43f30f3f67.zip
  .yarn/cache/xmlchars-npm-2.2.0-8b78f0f5e4-4ad5924974.zip
  extensions/awellTasks/CHANGELOG.md
  extensions/awellTasks/README.md
  extensions/awellTasks/actions/getComments/__testdata__/comments.mock.ts
  extensions/awellTasks/actions/getComments/config/dataPoints.ts
  extensions/awellTasks/actions/getComments/config/fields.ts
  extensions/awellTasks/actions/getComments/config/index.ts
  extensions/awellTasks/actions/getComments/getComments.test.ts
  extensions/awellTasks/actions/getComments/getComments.ts
  extensions/awellTasks/actions/getComments/index.ts
  extensions/awellTasks/actions/getComments/lib/htmlToEscapedJsString/htmlToEscapedJsString.test.ts
  extensions/awellTasks/actions/getComments/lib/htmlToEscapedJsString/htmlToEscapedJsString.ts
  extensions/awellTasks/actions/getComments/lib/htmlToEscapedJsString/index.ts
  extensions/awellTasks/actions/index.ts
  extensions/awellTasks/api/client.ts
  extensions/awellTasks/api/schema/GetCareflowComments.schema.ts
  extensions/awellTasks/api/schema/Pagination.schema.ts
  extensions/awellTasks/api/schema/User.schema.ts
  extensions/awellTasks/api/schema/index.ts
  extensions/awellTasks/index.ts
  extensions/awellTasks/lib/validatePayloadAndCreateSdk.ts
  extensions/awellTasks/settings.ts
  extensions/index.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: Review effort [1-5]: 4

#552 ET-790: Get last task performer
  extensions/awellTasks/actions/getLastTaskPerformer/__testdata__/completedTasks.mock.ts
  extensions/awellTasks/actions/getLastTaskPerformer/config/dataPoints.ts
  extensions/awellTasks/actions/getLastTaskPerformer/config/fields.ts
  extensions/awellTasks/actions/getLastTaskPerformer/config/index.ts
  extensions/awellTasks/actions/getLastTaskPerformer/getLastTaskPerformer.test.ts
  extensions/awellTasks/actions/getLastTaskPerformer/getLastTaskPerformer.ts
  extensions/awellTasks/actions/getLastTaskPerformer/index.ts
  extensions/awellTasks/actions/index.ts
  extensions/awellTasks/api/client.ts
  extensions/awellTasks/api/schema/GetTasks.schema.ts
  extensions/awellTasks/api/schema/index.ts
Labels: Review effort [1-5]: 4

#556 feat(collectData): enable arrayTest action in CollectData extension
  extensions/collectData/index.ts
  extensions/collectData/v1/actions/arrayTest/config/fields.ts
  extensions/collectData/v1/actions/index.ts
Labels: Review effort [1-5]: 2

#558 elation: find appointments using a prompt
  extensions/elation/__mocks__/constants.ts
  extensions/elation/actions/findAppointmentsByPrompt/__testdata__/GetAppointments.mock.ts
  extensions/elation/actions/findAppointmentsByPrompt/config/dataPoints.ts
  extensions/elation/actions/findAppointmentsByPrompt/config/fields.ts
  extensions/elation/actions/findAppointmentsByPrompt/config/index.ts
  extensions/elation/actions/findAppointmentsByPrompt/findAppointmentsByPrompt.test.ts
  extensions/elation/actions/findAppointmentsByPrompt/findAppointmentsByPrompt.ts
  extensions/elation/actions/findAppointmentsByPrompt/index.ts
  extensions/elation/actions/findFutureAppointment/findFutureAppointment.ts
  extensions/elation/actions/index.ts
  extensions/elation/validation/appointment.zod.ts
  package.json
Labels: Review effort [1-5]: 4

#559 TP-2828: Elation - sign note
  extensions/elation/actions/index.ts
  extensions/elation/actions/signNonVisitNote/config/dataPoints.ts
  extensions/elation/actions/signNonVisitNote/config/fields.ts
  extensions/elation/actions/signNonVisitNote/config/index.ts
  extensions/elation/actions/signNonVisitNote/index.ts
  extensions/elation/actions/signNonVisitNote/signNonVisitNote.test.ts
  extensions/elation/actions/signNonVisitNote/signNonVisitNote.ts
  extensions/elation/actions/updateNonVisitNote.ts
  package.json
  tests/createAxiosError.ts
  tests/index.ts
Labels: Review effort [1-5]: 3

#560 ET-806: Elation - update referral resolution
  extensions/elation/actions/createReferralOrder/createReferralOrder.ts
  extensions/elation/actions/index.ts
  extensions/elation/actions/updateReferralOrderResolution/config/dataPoints.ts
  extensions/elation/actions/updateReferralOrderResolution/config/fields.ts
  extensions/elation/actions/updateReferralOrderResolution/config/index.ts
  extensions/elation/actions/updateReferralOrderResolution/index.ts
  extensions/elation/actions/updateReferralOrderResolution/updateReferralOrderResolution.test.ts
  extensions/elation/actions/updateReferralOrderResolution/updateReferralOrderResolution.ts
  extensions/elation/client.ts
  extensions/elation/types/referralOrder.ts
Labels: Review effort [1-5]: 4

#557 ET-603: Add tests in arrayTest action and parse values
  extensions/collectData/v1/actions/arrayTest/arrayTest.test.ts
  extensions/collectData/v1/actions/arrayTest/config/fields.ts
Labels: Review effort [1-5]: 2

#561 elation: fix actions
  extensions/elation/actions/findAppointmentsByPrompt/findAppointmentsByPrompt.ts
  extensions/elation/actions/updatePatientTags/updatePatientTags.ts
Labels: Review effort [1-5]: 3

#563 refactor(getLastTaskPerformer): rename 'order_by' to 'direction' in t…
  extensions/awellTasks/actions/getLastTaskPerformer/getLastTaskPerformer.ts
  extensions/awellTasks/api/schema/GetTasks.schema.ts
Labels: Review effort [1-5]: 2

#567 Automate labeling and PR reviewer assignment for AI Actions
  .github/workflows/auto-assign-ai-actions.yml
  .github/workflows/pr_agent.yml
  .pr_agent.toml
Labels: Review effort [1-5]: 3

#569 ET-859: pretty text output for collect medication
  extensions/collectData/v1/actions/collectMedication/config/datapoints.ts
Labels: Review effort [1-5]: 2

#570 feat(awell): read data point value
  extensions/awell/README.md
  extensions/awell/index.ts
  extensions/awell/v1/actions/getDataPointValue/__testdata__/getDataPointValue.mock.ts
  extensions/awell/v1/actions/getDataPointValue/config/dataPoints.ts
  extensions/awell/v1/actions/getDataPointValue/config/fields.ts
  extensions/awell/v1/actions/getDataPointValue/config/index.ts
  extensions/awell/v1/actions/getDataPointValue/getDataPointValue.test.ts
  extensions/awell/v1/actions/getDataPointValue/getDataPointValue.ts
  extensions/awell/v1/actions/getDataPointValue/index.ts
  extensions/awell/v1/actions/index.ts
Labels: Review effort [1-5]: 4

#568 ET-825: Finalize Update Patient Tags AI Action
  extensions/elation/actions/updatePatientTags/config/dataPoints.ts
  extensions/elation/actions/updatePatientTags/config/fields.ts
  extensions/elation/actions/updatePatientTags/config/types.ts
  extensions/elation/actions/updatePatientTags/lib/getTagsFromLLM/evaluateTags.ts
  extensions/elation/actions/updatePatientTags/lib/getTagsFromLLM/getTagsFromLLM.ts
  extensions/elation/actions/updatePatientTags/lib/getTagsFromLLM/parser.ts
  extensions/elation/actions/updatePatientTags/lib/getTagsFromLLM/prompt.ts
  extensions/elation/actions/updatePatientTags/updatePatientTags.test.ts
  extensions/elation/actions/updatePatientTags/updatePatientTags.ts
  extensions/elation/actions/updatePatientTags/updatePatientTagsRealOpenAI.test.ts
  extensions/elation/actions/updatePatientTags/updateTags.ts
Labels: Review effort [1-5]: 4

#571 feat(openai): increase timeout and retry attempts
  src/lib/llm/openai/constants.ts
Labels: Review effort [1-5]: 1

#572 chore(): help paloma debug healthie failures
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/logs/getSubActivityLogs/getSubActivityLogs.ts
  extensions/healthie/actions/dataExchange/pushFormResponsesToHealthie/pushFormResponsesToHealthie.ts
Labels: Review effort [1-5]: 4
