Repository awell-health/awell-extensions, pull requests merged in 2025-06, with the labels that each got.

#642 feat(healthie): add record identifier fields
  extensions/healthie/actions/createPatient/config/fields.ts
  extensions/healthie/actions/createPatient/createPatient.ts
  extensions/healthie/actions/updatePatient/config/fields.ts
  extensions/healthie/actions/updatePatient/config/index.ts
  extensions/healthie/actions/updatePatient/updatePatient.ts
Labels: Review effort 3/5

#643 feat(braze): app id at the settings level
  extensions/braze/README.md
  extensions/braze/actions/scheduleEmail/config.ts
  extensions/braze/actions/scheduleEmail/scheduleEmail.test.ts
  extensions/braze/actions/scheduleEmail/scheduleEmail.ts
  extensions/braze/actions/scheduleSMS/config.ts
  extensions/braze/actions/scheduleSMS/scheduleSMS.test.ts
  extensions/braze/actions/scheduleSMS/scheduleSMS.ts
  extensions/braze/actions/sendCampaign/sendCampaign.test.ts
  extensions/braze/actions/sendCampaign/sendCampaign.ts
  extensions/braze/actions/sendEmail/config.ts
  extensions/braze/actions/sendEmail/sendEmail.test.ts
  extensions/braze/actions/sendEmail/sendEmail.ts
  extensions/braze/actions/sendEmailUsingTemplate/config.ts
  extensions/braze/actions/sendEmailUsingTemplate/sendEmailUsingTemplate.test.ts
  extensions/braze/actions/sendEmailUsingTemplate/sendEmailUsingTemplate.ts
  extensions/braze/actions/sendSMS/config.ts
  extensions/braze/actions/sendSMS/sendSMS.test.ts
  extensions/braze/actions/sendSMS/sendSMS.ts
  extensions/braze/lib/api/client.ts
  extensions/braze/lib/validateAndCreateClient.test.ts
  extensions/braze/lib/validateAndCreateClient.ts
  extensions/braze/settings.ts
Labels: Review effort 4/5

#644 rev-243-add-an-instructions-field-to-the-ai-categorization-action
  extensions/shelly/actions/categorizeMessage/categorizeMessage.ts
  extensions/shelly/actions/categorizeMessage/config/fields.ts
  extensions/shelly/actions/categorizeMessage/lib/categorizeMessageWithLLM/categorizeMessageWithLLM.ts
  extensions/shelly/actions/categorizeMessage/lib/categorizeMessageWithLLM/prompt.ts
Labels: Review effort 2/5

#648 feat(transform): make text-to-phone more foregiving
  extensions/bland/webhooks/CallCompleted/callCompleted.test.ts
  extensions/bland/webhooks/CallCompleted/callCompleted.ts
  extensions/transform/v1/actions/parseStringToPhoneNumber/config/fields.ts
  extensions/transform/v1/actions/parseStringToPhoneNumber/parseStringToPhoneNumber.test.ts
  extensions/transform/v1/actions/parseStringToPhoneNumber/parseStringToPhoneNumber.ts
Labels: Review effort 3/5
