Repository awell-health/awell-extensions, pull requests merged in 2025-04, with the labels that each got.

#623 REV-153: refactor create patient + error handling
  extensions/elation/README.md
  extensions/elation/actions/__tests__/createPatient.ts
  extensions/elation/actions/createPatient.ts
  extensions/elation/actions/createPatient/__testdata__/createPatient.mock.ts
  extensions/elation/actions/createPatient/config/dataPoints.ts
  extensions/elation/actions/createPatient/config/fields.ts
  extensions/elation/actions/createPatient/config/index.ts
  extensions/elation/actions/createPatient/createPatient.test.ts
  extensions/elation/actions/createPatient/createPatient.ts
  extensions/elation/actions/createPatient/index.ts
  extensions/elation/client.ts
  extensions/elation/validation/patient.zod.ts
Labels: Review effort 4/5

#625 chore(): bland update
  extensions/bland/README.md
  extensions/bland/actions/getCallDetails/__tests__/getCallDetails.test.ts
  extensions/bland/actions/getCallDetails/config/dataPoints.ts
  extensions/bland/actions/getCallDetails/config/fields.ts
  extensions/bland/actions/getCallDetails/getCallDetails.ts
  extensions/bland/actions/sendCall/__tests__/sendCall.test.ts
  extensions/bland/actions/sendCall/config/dataPoints.ts
  extensions/bland/actions/sendCall/config/fields.ts
  extensions/bland/actions/sendCall/sendCall.ts
  extensions/bland/actions/sendCallWithPathway/__tests__/sendCallWithPathway.test.ts
  extensions/bland/actions/sendCallWithPathway/config/dataPoints.ts
  extensions/bland/actions/sendCallWithPathway/config/fields.ts
  extensions/bland/actions/sendCallWithPathway/sendCallWithPathway.test.ts
  extensions/bland/actions/sendCallWithPathway/sendCallWithPathway.ts
  extensions/bland/api/schema/GetCallDetails.schema.ts
  extensions/bland/api/schema/SendCall.schema.ts
  extensions/bland/api/schema/atoms/BackgroundTrackSchema.ts
  extensions/bland/api/schema/atoms/ModelSchema.ts
  extensions/bland/api/schema/atoms/VoicemailActionSchema.ts
  extensions/bland/api/schema/atoms/WebhookEventsSchema.ts
  extensions/bland/api/schema/atoms/index.ts
  extensions/bland/index.ts
  extensions/bland/lib/sharedActionFields.ts
  extensions/bland/webhooks/CallCompleted/README.md
  extensions/bland/webhooks/CallCompleted/__testdata__/callCompleted.mock.ts
  extensions/bland/webhooks/CallCompleted/callCompleted.test.ts
  extensions/bland/webhooks/CallCompleted/callCompleted.ts
  extensions/bland/webhooks/CallCompleted/index.ts
  extensions/bland/webhooks/CallCompleted/types.ts
  extensions/bland/webhooks/index.ts
Labels: Review effort 4/5

#626 REV-176: list form answers action
  extensions/awell/index.ts
  extensions/awell/v1/actions/index.ts
  extensions/awell/v1/actions/listFormAnswers/__testdata__/formDefinitionResponse.ts
  extensions/awell/v1/actions/listFormAnswers/__testdata__/formResponseResponse.ts
  extensions/awell/v1/actions/listFormAnswers/__testdata__/index.ts
  extensions/awell/v1/actions/listFormAnswers/__testdata__/pathwayActivitiesResponse.ts
  extensions/awell/v1/actions/listFormAnswers/config/dataPoints.ts
  extensions/awell/v1/actions/listFormAnswers/config/fields.ts
  extensions/awell/v1/actions/listFormAnswers/config/index.ts
  extensions/awell/v1/actions/listFormAnswers/index.ts
  extensions/awell/v1/actions/listFormAnswers/lib/generateFormOutput.ts
  extensions/awell/v1/actions/listFormAnswers/listFormAnswers.test.ts
  extensions/awell/v1/actions/listFormAnswers/listFormAnswers.ts
Labels: Review effort 4/5

#627 Date utils: Get next workday
  extensions/awell/v1/actions/listFormAnswers/listFormAnswers.test.ts
  extensions/dateHelpers/CHANGELOG.md
  extensions/dateHelpers/README.md
  extensions/dateHelpers/actions/getNextWorkday/config/dataPoints.ts
  extensions/dateHelpers/actions/getNextWorkday/config/fields.ts
  extensions/dateHelpers/actions/getNextWorkday/config/index.ts
  extensions/dateHelpers/actions/getNextWorkday/getNextWorkday.test.ts
  extensions/dateHelpers/actions/getNextWorkday/getNextWorkday.ts
  extensions/dateHelpers/actions/getNextWorkday/index.ts
  extensions/dateHelpers/actions/index.ts
  extensions/dateHelpers/index.ts
  extensions/dateHelpers/settings.ts
Labels: Review effort 3/5

#628 feat(elation): remove 10 tags restriction
  extensions/elation/actions/updatePatientTags/lib/getTagsFromLLM/evaluateTags.ts
  extensions/elation/actions/updatePatientTags/lib/getTagsFromLLM/prompt.ts
Labels: Review effort 2/5

#629 feat(elation): minor improvements to FindAppointments prompt
  extensions/elation/lib/findAppointmentsWithLLM/FindAppointmentsWithLLM.evaluate.ts
  extensions/elation/lib/findAppointmentsWithLLM/prompt.ts
Labels: ai-action, Review effort 2/5
