Repository awell-health/awell-extensions, pull requests merged in 2025-02, with the labels that each got.

#574 fix(metriport): broken and outdated npm package needed updating
  .pnp.cjs
  .yarn/cache/@medplum-core-npm-2.2.10-8e18934a52-15c9032097.zip
  .yarn/cache/@medplum-fhirtypes-npm-2.2.10-d97a6096b5-1592afd4ca.zip
  .yarn/cache/@metriport-api-npm-3.1.6-ec77cead16-2939919a00.zip
  .yarn/cache/@metriport-api-sdk-npm-14.11.1-b3e09c8fb9-c85152aa00.zip
  .yarn/cache/@metriport-commonwell-sdk-npm-5.5.2-1d4734b30c-edf47868b2.zip
  .yarn/cache/@metriport-shared-npm-0.19.2-30df8385af-3dde70b047.zip
  .yarn/cache/@parcel-watcher-darwin-arm64-npm-2.4.1-7294eb72cd-10.zip
  .yarn/cache/@parcel-watcher-darwin-x64-npm-2.4.1-e905ba5776-10.zip
  .yarn/cache/axios-npm-1.7.9-3c98466f87-b7a5f660ea.zip
  .yarn/cache/fast-xml-parser-npm-4.5.1-77d072daa3-17ce5908e7.zip
  .yarn/cache/http-status-npm-1.7.4-bbe8693c7b-6b510d2532.zip
  .yarn/cache/strnum-npm-1.0.5-9ba11d2a0a-d3117975db.zip
  .yarn/cache/zod-npm-3.23.8-11c49c85b5-846fd73e1a.zip
  .yarn/cache/zod-npm-3.24.1-62ba4e84b3-54e2595649.zip
  extensions/metriport/actions/document/dataPoints.ts
  extensions/metriport/actions/document/fields.ts
  extensions/metriport/actions/document/list.ts
  extensions/metriport/actions/document/query.ts
  extensions/metriport/actions/patient/create.ts
  extensions/metriport/actions/patient/validation.ts
  extensions/metriport/client.ts
  package.json
  yarn.lock
Labels: Review effort [1-5]: 4

#575 chore(metriport): temporarily remove metriport until api-sdk doesn't cause build errors
  .pnp.cjs
  .yarn/cache/@medplum-core-npm-2.2.10-8e18934a52-15c9032097.zip
  .yarn/cache/@medplum-fhirtypes-npm-2.2.10-d97a6096b5-1592afd4ca.zip
  .yarn/cache/@metriport-api-sdk-npm-14.11.1-b3e09c8fb9-c85152aa00.zip
  .yarn/cache/@metriport-commonwell-sdk-npm-5.5.2-1d4734b30c-edf47868b2.zip
  .yarn/cache/@metriport-shared-npm-0.19.2-30df8385af-3dde70b047.zip
  .yarn/cache/axios-npm-1.7.9-3c98466f87-b7a5f660ea.zip
  .yarn/cache/fast-xml-parser-npm-4.5.1-77d072daa3-17ce5908e7.zip
  .yarn/cache/http-status-npm-1.7.4-bbe8693c7b-6b510d2532.zip
  .yarn/cache/strnum-npm-1.0.5-9ba11d2a0a-d3117975db.zip
  extensions/index.ts
  extensions/metriport/actions/patient/create.ts
  extensions/metriport/actions/patient/get.ts
  extensions/metriport/actions/patient/validation.ts
  extensions/metriport/client.ts
  package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#576 Et 824 add new elation action
  extensions/elation/actions/__tests__/createMessageThread.ts
  extensions/elation/actions/addMessageToThread/addMessageToThread.test.ts
  extensions/elation/actions/addMessageToThread/addMessageToThread.ts
  extensions/elation/actions/addMessageToThread/config/dataPoints.ts
  extensions/elation/actions/addMessageToThread/config/fields.ts
  extensions/elation/actions/addMessageToThread/config/index.ts
  extensions/elation/actions/addMessageToThread/index.ts
  extensions/elation/actions/createMessageThread.ts
  extensions/elation/actions/createMessageThread/config/dataPoints.ts
  extensions/elation/actions/createMessageThread/config/fields.ts
  extensions/elation/actions/createMessageThread/config/index.ts
  extensions/elation/actions/createMessageThread/createMessageThread.test.ts
  extensions/elation/actions/createMessageThread/createMessageThread.ts
  extensions/elation/actions/createMessageThread/index.ts
  extensions/elation/actions/index.ts
  extensions/elation/client.ts
  extensions/elation/types/messageThread.ts
  extensions/elation/validation/messageThread.zod.ts
Labels: Review effort [1-5]: 4

#583 Elation: Improvements for Find Appointments AI Actions
  extensions/elation/README.md
  extensions/elation/actions/findAppointmentsByPrompt/index.ts
  extensions/elation/actions/findAppointmentsByPrompt/lib/findAppointmentsByPromptWithLLM/prompt.ts
  extensions/elation/actions/findAppointmentsWithAI/__testdata__/GetAppointments.mock.ts
  extensions/elation/actions/findAppointmentsWithAI/config/dataPoints.ts
  extensions/elation/actions/findAppointmentsWithAI/config/fields.ts
  extensions/elation/actions/findAppointmentsWithAI/config/index.ts
  extensions/elation/actions/findAppointmentsWithAI/findAppointmentsWithAI.test.ts
  extensions/elation/actions/findAppointmentsWithAI/findAppointmentsWithAI.ts
  extensions/elation/actions/findAppointmentsWithAI/findAppointmentsWithAIRealOpenAI.test.ts
  extensions/elation/actions/findAppointmentsWithAI/getAppoitnmentCountByStatus.ts
  extensions/elation/actions/findAppointmentsWithAI/index.ts
  extensions/elation/actions/findFutureAppointment/findFutureAppointment.test.ts
  extensions/elation/actions/findFutureAppointment/findFutureAppointment.ts
  extensions/elation/actions/findFutureAppointment/findFutureAppointmentRealOpenAI.test.ts
  extensions/elation/actions/findFutureAppointment/formatAppointments.ts
  extensions/elation/actions/findFutureAppointment/getFutureAppointments.ts
  extensions/elation/actions/findFutureAppointment/lib/findAppointmentWithLLM/findAppointmentWithLLM.ts
  extensions/elation/actions/findFutureAppointment/lib/findAppointmentWithLLM/parser.ts
  extensions/elation/actions/findFutureAppointment/lib/findAppointmentWithLLM/prompt.ts
  extensions/elation/actions/index.ts
  extensions/elation/actions/updatePatientTags/updatePatientTags.ts
  extensions/elation/lib/findAppointmentsWithLLM/FindAppointmentsWithLLM.evaluate.ts
  extensions/elation/lib/findAppointmentsWithLLM/findAppointmentsWithLLM.ts
  extensions/elation/lib/findAppointmentsWithLLM/parser.ts
  extensions/elation/lib/findAppointmentsWithLLM/prompt.ts
Labels: Review effort [1-5]: 4, ai-action

#585 fix(elation): add datetime awareness to findAppointmentsWithLLM
  extensions/elation/actions/findAppointmentsWithAI/__testdata__/GetAppointments.mock.ts
  extensions/elation/actions/findAppointmentsWithAI/findAppointmentsWithAIRealOpenAI.test.ts
  extensions/elation/actions/findFutureAppointment/__testdata__/GetAppointments.mock.ts
  extensions/elation/actions/findFutureAppointment/findFutureAppointmentRealOpenAI.test.ts
  extensions/elation/lib/findAppointmentsWithLLM/findAppointmentsWithLLM.ts
  extensions/elation/lib/findAppointmentsWithLLM/prompt.ts
Labels: Review effort [1-5]: 4, ai-action

#586 fix(elation): elation settings schema is broken
  extensions/elation/settings.ts
  extensions/elation/validation/nonVisitNote.zod.ts
  extensions/elation/webhooks/appointmentCreatedOrUpdated.ts
  extensions/elation/webhooks/patientCreatedOrUpdated.ts
  extensions/elation/webhooks/rateLimitValidation.test.ts
Labels: Review effort [1-5]: 4

#587 Elation: non-visit note refactor
  extensions/elation/actions/__tests__/createNonVisitNote.ts
  extensions/elation/actions/createNonVisitNote.ts
  extensions/elation/actions/createNonVisitNote/__testdata__/CreateNonVisitNote.mock.ts
  extensions/elation/actions/createNonVisitNote/config/dataPoints.ts
  extensions/elation/actions/createNonVisitNote/config/fields.ts
  extensions/elation/actions/createNonVisitNote/config/index.ts
  extensions/elation/actions/createNonVisitNote/createNonVisitNote.test.ts
  extensions/elation/actions/createNonVisitNote/createNonVisitNote.ts
  extensions/elation/actions/createNonVisitNote/index.ts
  extensions/elation/actions/index.ts
  extensions/elation/client.ts
Labels: Review effort [1-5]: 4

#589 TP-2876-fix-incorrect-arg
  extensions/awell/v1/actions/isPatientEnrolledInCareFlow/isPatientEnrolledInCareFlow.ts
Labels: Review effort 3/5

#590 add medplum webhook - createPatient
  extensions/medplum/index.ts
  extensions/medplum/webhooks/index.ts
  extensions/medplum/webhooks/patientCreated.ts
Labels: Review effort 3/5

#592 Et 1026 add braze extension
  extensions/braze/CHANGELOG.md
  extensions/braze/README.md
  extensions/braze/actions/actionHelpers.ts
  extensions/braze/actions/index.ts
  extensions/braze/actions/scheduleEmail/config.ts
  extensions/braze/actions/scheduleEmail/index.ts
  extensions/braze/actions/scheduleEmail/scheduleEmail.test.ts
  extensions/braze/actions/scheduleEmail/scheduleEmail.ts
  extensions/braze/actions/scheduleSMS/config.ts
  extensions/braze/actions/scheduleSMS/index.ts
  extensions/braze/actions/scheduleSMS/scheduleSMS.test.ts
  extensions/braze/actions/scheduleSMS/scheduleSMS.ts
  extensions/braze/actions/sendEmail/config.ts
  extensions/braze/actions/sendEmail/index.ts
  extensions/braze/actions/sendEmail/sendEmail.test.ts
  extensions/braze/actions/sendEmail/sendEmail.ts
  extensions/braze/actions/sendEmailUsingTemplate/config.ts
  extensions/braze/actions/sendEmailUsingTemplate/index.ts
  extensions/braze/actions/sendEmailUsingTemplate/sendEmailUsingTemplate.test.ts
  extensions/braze/actions/sendEmailUsingTemplate/sendEmailUsingTemplate.ts
  extensions/braze/actions/sendSMS/config.ts
  extensions/braze/actions/sendSMS/index.ts
  extensions/braze/actions/sendSMS/sendSMS.test.ts
  extensions/braze/actions/sendSMS/sendSMS.ts
  extensions/braze/client.ts
  extensions/braze/index.ts
  extensions/braze/settings.ts
  extensions/index.ts
Labels: Review effort 5/5

#593 feat(elation): cancel appointments
  extensions/elation/README.md
  extensions/elation/actions/cancelAppointments/__testdata__/Findappointments.mock.ts
  extensions/elation/actions/cancelAppointments/cancelAppointments.test.ts
  extensions/elation/actions/cancelAppointments/cancelAppointments.ts
  extensions/elation/actions/cancelAppointments/cancelAppointmentsWithAIRealOpenAI.test.ts
  extensions/elation/actions/cancelAppointments/config/dataPoints.ts
  extensions/elation/actions/cancelAppointments/config/fields.ts
  extensions/elation/actions/cancelAppointments/config/index.ts
  extensions/elation/actions/cancelAppointments/index.ts
  extensions/elation/actions/index.ts
  extensions/elation/client.ts
  extensions/elation/types/appointment.ts
Labels: Review effort 4/5
