Repository awell-health/awell-extensions, pull requests merged in 2025-09, with the labels that each got.

#697 rename to zendeskSell
  extensions/index.ts
  extensions/zendesk/README.md
  extensions/zendeskSell/CHANGELOG.md
  extensions/zendeskSell/README.md
  extensions/zendeskSell/index.ts
  extensions/zendeskSell/settings.ts
  extensions/zendeskSell/v1/actions/completeTask/completeTask.test.ts
  extensions/zendeskSell/v1/actions/completeTask/completeTask.ts
  extensions/zendeskSell/v1/actions/completeTask/config/fields.ts
  extensions/zendeskSell/v1/actions/completeTask/config/index.ts
  extensions/zendeskSell/v1/actions/completeTask/index.ts
  extensions/zendeskSell/v1/actions/createTask/config/dataPoints.ts
  extensions/zendeskSell/v1/actions/createTask/config/fields.ts
  extensions/zendeskSell/v1/actions/createTask/config/index.ts
  extensions/zendeskSell/v1/actions/createTask/createTask.test.ts
  extensions/zendeskSell/v1/actions/createTask/createTask.ts
  extensions/zendeskSell/v1/actions/createTask/index.ts
  extensions/zendeskSell/v1/actions/index.ts
  extensions/zendeskSell/v1/client/__mocks__/client.ts
  extensions/zendeskSell/v1/client/__mocks__/index.ts
  extensions/zendeskSell/v1/client/__mocks__/testData.ts
  extensions/zendeskSell/v1/client/client.ts
  extensions/zendeskSell/v1/client/error.ts
  extensions/zendeskSell/v1/client/index.ts
  extensions/zendeskSell/v1/client/types.ts
  extensions/zendeskSell/v1/types.ts
Labels: Review effort 3/5

#701 fix-on-create-ticket
  extensions/zendesk/v1/actions/createTicket/createTicket.test.ts
  extensions/zendesk/v1/actions/createTicket/createTicket.ts
Labels: Review effort 2/5

#705 fix build
  components/hello-world/frontend/index.tsx
  extensions/canvasMedical/v1/actions/createClaim/createClaim.test.ts
  extensions/canvasMedical/v1/actions/updateCoverage/updateCoverage.test.ts
  extensions/epic/lib/api/FhirR4/FhirR4client.ts
  extensions/mailchimp/v1/actions/sendEmail/sendEmail.test.ts
  extensions/mailchimp/v1/actions/sendEmail/sendEmail.ts
  extensions/mailchimp/v1/actions/sendEmailWithTemplate/sendEmailWithTemplate.test.ts
  extensions/transform/v1/actions/parseNumberToText/parseNumberToText.test.ts
Labels: Review effort 1/5

#707 Additional-extension-actions
  extensions/awell/v1/actions/stopTrack/config/fields.ts
  extensions/awell/v1/actions/stopTrack/stopTrack.test.ts
  extensions/awell/v1/actions/stopTrack/stopTrack.ts
  extensions/dateHelpers/actions/checkWorkingHours/checkWorkingHours.test.ts
  extensions/dateHelpers/actions/checkWorkingHours/checkWorkingHours.ts
  extensions/dateHelpers/actions/checkWorkingHours/config/dataPoints.ts
  extensions/dateHelpers/actions/checkWorkingHours/config/fields.ts
  extensions/dateHelpers/actions/checkWorkingHours/config/index.ts
  extensions/dateHelpers/actions/checkWorkingHours/index.ts
  extensions/dateHelpers/actions/index.ts
Labels: Review effort 3/5

#708 feat(dateHelpers): add nextWorkingHoursDatetime to checkWorkingHours action
  extensions/dateHelpers/actions/checkWorkingHours/checkWorkingHours.test.ts
  extensions/dateHelpers/actions/checkWorkingHours/checkWorkingHours.ts
  extensions/dateHelpers/actions/checkWorkingHours/config/dataPoints.ts
Labels: Review effort 2/5

#709 fix: use proper date type for working hours action
  extensions/dateHelpers/actions/checkWorkingHours/config/dataPoints.ts
Labels: Review effort 1/5

#713 Awl 3035 add is patient already enrolled in track query
  extensions/awell/v1/actions/index.ts
  extensions/awell/v1/actions/isPatientEnrolledInTrack/config/dataPoints.ts
  extensions/awell/v1/actions/isPatientEnrolledInTrack/config/fields.ts
  extensions/awell/v1/actions/isPatientEnrolledInTrack/config/index.ts
  extensions/awell/v1/actions/isPatientEnrolledInTrack/config/pathway.ts
  extensions/awell/v1/actions/isPatientEnrolledInTrack/index.ts
  extensions/awell/v1/actions/isPatientEnrolledInTrack/isPatientEnrolledInTrack.test.ts
  extensions/awell/v1/actions/isPatientEnrolledInTrack/isPatientEnrolledInTrack.ts
  extensions/epic/actions/getClinicalNote/getClinicalNote.test.ts
Labels: Review effort 2/5

#716 feat: improve date filtering in findAppointmentsWithAI
  extensions/elation/actions/findAppointmentsWithAI/findAppointmentsWithAI.test.ts
  extensions/elation/actions/findAppointmentsWithAI/findAppointmentsWithAI.ts
Labels: Review effort 2/5
