Repository awell-health/awell-extensions, pull requests merged in 2025-05, with the labels that each got.

#632 feat(customerIo): track person event
  extensions/customerIo/CHANGELOG.md
  extensions/customerIo/README.md
  extensions/customerIo/actions/index.ts
  extensions/customerIo/actions/trackPersonEvent/config/datapoints.ts
  extensions/customerIo/actions/trackPersonEvent/config/fields.ts
  extensions/customerIo/actions/trackPersonEvent/config/index.ts
  extensions/customerIo/actions/trackPersonEvent/index.ts
  extensions/customerIo/actions/trackPersonEvent/trackPersonEvent.test.ts
  extensions/customerIo/actions/trackPersonEvent/trackPersonEvent.ts
  extensions/customerIo/index.ts
  extensions/customerIo/lib/api/index.ts
  extensions/customerIo/lib/api/schema/TrackPersonEvent.schema.ts
  extensions/customerIo/lib/api/schema/atoms/ActionType.schema.ts
  extensions/customerIo/lib/api/schema/atoms/EventType.schema.ts
  extensions/customerIo/lib/api/schema/atoms/index.ts
  extensions/customerIo/lib/api/schema/index.ts
  extensions/customerIo/lib/api/trackApiClient.ts
  extensions/customerIo/lib/index.ts
  extensions/customerIo/lib/validatePayloadAndCreateSdk.ts
  extensions/customerIo/settings.ts
  extensions/index.ts
Labels: Review effort 3/5

#633 REV-172: Zoom Extension
  extensions/index.ts
  extensions/zoom/CHANGELOG.md
  extensions/zoom/README.md
  extensions/zoom/actions/index.ts
  extensions/zoom/actions/sendSms/config/dataPoints.ts
  extensions/zoom/actions/sendSms/config/fields.ts
  extensions/zoom/actions/sendSms/config/index.ts
  extensions/zoom/actions/sendSms/index.ts
  extensions/zoom/actions/sendSms/sendSms.test.ts
  extensions/zoom/actions/sendSms/sendSms.ts
  extensions/zoom/index.ts
  extensions/zoom/lib/api/client.ts
  extensions/zoom/lib/api/constants.ts
  extensions/zoom/lib/api/schema/SendSms.schema.ts
  extensions/zoom/lib/api/schema/index.ts
  extensions/zoom/lib/validatePayloadAndCreateSdk.ts
  extensions/zoom/settings.ts
Labels: Review effort 4/5

#635 Vis 230 update extensions to use the same regex and not zod email
  extensions/athenahealth/actions/createPatient/config/fields.ts
  extensions/awell/v1/actions/updatePatient/config/fields.ts
  extensions/cerner/actions/createPatient/config/fields.ts
  extensions/customerIo/lib/api/schema/TrackPersonEvent.schema.ts
  extensions/elation/actions/createPatient/config/fields.ts
  extensions/elation/validation/patient.zod.ts
  extensions/elation/validation/physician.zod.ts
  extensions/epic/actions/createPatient/config/fields.ts
  extensions/epic/actions/matchPatient/config/fields.ts
  extensions/healthie/actions/createPatient/config/fields.ts
  extensions/healthie/actions/updatePatient/config/fields.ts
  extensions/hubspot/actions/createOrUpdateContact/config/fields.ts
  extensions/infobip/settings.ts
  extensions/medplum/fhir/schemas/resources/patient.schema.ts
  extensions/metriport/actions/patient/validation.ts
  extensions/stripe/actions/createCustomer/config/fields.ts
  extensions/workramp/types/EventPayload.ts
  src/utils/emailValidation.ts
  src/utils/index.ts
Labels: Review effort 3/5

#636 VIS-216: Improve AI Action Summarize Form
  extensions/shelly/lib/summarizeFormWithLLM/prompt.ts
  extensions/shelly/lib/summarizeFormWithLLM/summarizeFormWithLLM.evaluate.ts
Labels: ai-action

#637 VIS-110: Add Language Detection to SUmmarize Form AI Actions
  extensions/shelly/actions/summarizeForm/summarizeForm.test.ts
  extensions/shelly/actions/summarizeForm/summarizeForm.ts
  extensions/shelly/actions/summarizeForm/summarizeFormRealOpenAI.test.ts
  extensions/shelly/actions/summarizeFormsInStep/summarizeFormsInStep.test.ts
  extensions/shelly/actions/summarizeFormsInStep/summarizeFormsInStep.ts
  extensions/shelly/actions/summarizeFormsInStep/summarizeFormsInStepRealOpenAI.test.ts
  extensions/shelly/lib/detectLanguageWithLLM/detectLanguageWithLLM.evaluate.ts
  extensions/shelly/lib/detectLanguageWithLLM/detectLanguageWithLLM.test.ts
  extensions/shelly/lib/detectLanguageWithLLM/detectLanguageWithLLM.ts
  extensions/shelly/lib/detectLanguageWithLLM/index.ts
  extensions/shelly/lib/detectLanguageWithLLM/prompt.ts
  extensions/shelly/lib/summarizeFormWithLLM/prompt.ts
Labels: ai-action, Review effort 4/5

#638 rev-196-add-new-braze-actions
  extensions/braze/README.md
  extensions/braze/actions/index.ts
  extensions/braze/actions/sendEmailWithAttributes/config.ts
  extensions/braze/actions/sendEmailWithAttributes/index.ts
  extensions/braze/actions/sendEmailWithAttributes/sendEmailWithAttributes.test.ts
  extensions/braze/actions/sendEmailWithAttributes/sendEmailWithAttributes.ts
  extensions/braze/client.ts
Labels: Review effort 2/5

#639 VIS-99: Better documentation for ai actions
  extensions/elation/README.md
  extensions/shelly/README.md
  extensions/shelly/actions/categorizeMessage/categorizeMessage.ts
  extensions/shelly/actions/generateMessage/generateMessage.ts
  extensions/shelly/actions/medicationFromImage/medicationFromImage.ts
  extensions/shelly/actions/summarizeCareFlow/summarizeCareFlow.ts
  extensions/shelly/index.ts
Labels: Review effort 2/5

#641 feat(cal): get-booking v2 api
  extensions/calDotCom/actions/bookAppointment/bookAppointment.ts
  extensions/calDotCom/actions/createBooking/createBooking.test.ts
  extensions/calDotCom/actions/createBooking/createBooking.ts
  extensions/calDotCom/actions/deleteBooking/deleteBooking.test.ts
  extensions/calDotCom/actions/deleteBooking/deleteBooking.ts
  extensions/calDotCom/actions/getBooking/index.ts
  extensions/calDotCom/actions/getBooking/v1/config/dataPoints.ts
  extensions/calDotCom/actions/getBooking/v1/config/fields.ts
  extensions/calDotCom/actions/getBooking/v1/config/index.ts
  extensions/calDotCom/actions/getBooking/v1/getBooking.test.ts
  extensions/calDotCom/actions/getBooking/v1/getBooking.ts
  extensions/calDotCom/actions/getBooking/v1/index.ts
  extensions/calDotCom/actions/getBooking/v2/__testdata__/GetBookingMockResponse.ts
  extensions/calDotCom/actions/getBooking/v2/config/dataPoints.ts
  extensions/calDotCom/actions/getBooking/v2/config/fields.ts
  extensions/calDotCom/actions/getBooking/v2/config/index.ts
  extensions/calDotCom/actions/getBooking/v2/getBooking.test.ts
  extensions/calDotCom/actions/getBooking/v2/getBooking.ts
  extensions/calDotCom/actions/getBooking/v2/index.ts
  extensions/calDotCom/actions/updateBooking/updateBooking.test.ts
  extensions/calDotCom/actions/updateBooking/updateBooking.ts
  extensions/calDotCom/index.ts
  extensions/calDotCom/lib/api/v1/__mocks__/calComApi.ts
  extensions/calDotCom/lib/api/v1/calComApi.ts
  extensions/calDotCom/lib/api/v1/schema.ts
  extensions/calDotCom/lib/api/v2/client.ts
  extensions/calDotCom/lib/api/v2/schema/GetBooking.schema.ts
  extensions/calDotCom/lib/api/v2/schema/Response.schema.ts
  extensions/calDotCom/lib/api/v2/schema/atoms/BookingStatus.schema.ts
  extensions/calDotCom/lib/api/v2/schema/atoms/index.ts
  extensions/calDotCom/lib/api/v2/schema/index.ts
  extensions/calDotCom/lib/api/validatePayloadAndCreateSdk.ts
  extensions/calDotCom/settings.ts
  extensions/medplum/actions/executeBot/executeBot.test.ts
Labels: Review effort 4/5
